version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

  bolt:
    image: node:20-alpine
    container_name: bolt
    working_dir: /app
    volumes:
      - ./bolt.diy:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"
    restart: unless-stopped

volumes:
  ollama:
  qdrant_data:
