version: '3.8'

services:
  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             capabilities: [compute, utility]
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped


  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    ports:
      - "3100:3080"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/librechat
    volumes:
      - ./librechat/librechat.yaml:/app/librechat.yaml:ro
      - librechat_data:/app/librechat
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: librechat-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - librechat_mongo_data:/data/db


  # bolt:
  #   build:
  #     context: ./bolt
  #     dockerfile: Dockerfile
  #     target: bolt-ai-development
  #   container_name: bolt
  #   working_dir: /app
  #   volumes:
  #     - shared_app:/app
  #   ports:
  #     - "5173:5173"
  #   profiles:
  #     - development
  #   environment:
  #     - HOST=0.0.0.0
  #   restart: unless-stopped

  llamaindex:
    build:
      context: ./llamaindex
      dockerfile: Dockerfile
    container_name: llamaindex
    working_dir: /app
    volumes:
      - ./llamaindex:/app  # ✅ contains main.py and is your real project source
    ports:
      - "8081:8081"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_API=http://ollama:11434
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

  langchain:
    build:
      context: ./langchain-agent
      dockerfile: Dockerfile
    container_name: langchain
    ports:
      - "8082:8082"
    depends_on:
      - llamaindex
      - ollama
    restart: unless-stopped

volumes:
  ollama:
  qdrant_data:
  shared_app:
  librechat_data:
  librechat_mongo_data:


